
version: '1.6.{build}'
image: Visual Studio 2017
clone_depth: 1
skip_tags: true
skip_branch_with_pr: true

environment:
  include_integration_tests: true

install:
  # Download script helper to convert Pester coverage into coverage JSON format for codecov
  - ps: |
      Install-Module Pester -Scope CurrentUser -Force -SkipPublisherCheck
      $uri = 'https://raw.githubusercontent.com/PowerShell/DscResource.Tests/491688867dc53894b92ca53520a18d145deb7760/DscResource.CodeCoverage/CodeCovIo.psm1'
      Invoke-WebRequest -Uri $uri -OutFile $env:USERPROFILE\CodeCovIo.psm1

build: off

test_script:
  # Run tests, upload test results and generate coverage report
  - ps: |
      Import-Module $env:USERPROFILE\CodeCovIo.psm1
      $testResultsFile = ".\TestsResults.xml"
      $res = Invoke-Pester -OutputFormat NUnitXml -OutputFile $testResultsFile -PassThru -CodeCoverage nvm.psm1 -CodeCoverageOutputFile coverage.xml
      (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $testResultsFile))
      Export-CodeCovIoJson -CodeCoverage $res.CodeCoverage -RepoRoot $pwd -Path coverage.json;
      if ($res.FailedCount -gt 0) {
          throw "$($res.FailedCount) tests failed."
      }

after_test:
  # Upload coverage report to codecov
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f coverage.json
